/* 
 * Gestão de Contratos
 *
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Entidade representando um cancelamento de um contrato.
    /// </summary>
    [DataContract]
    public partial class CancelamentoContratoResponse :  IEquatable<CancelamentoContratoResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CancelamentoContratoResponse" /> class.
        /// </summary>
        /// <param name="Contrato">Código do contrato..</param>
        /// <param name="Mensagem">Mensagem do retorno do cancelamento..</param>
        /// <param name="Comprovante">Comprovante de Cancelamento no seguinte formato..</param>
        public CancelamentoContratoResponse(string Contrato = default(string), string Mensagem = default(string), string Comprovante = default(string))
        {
            this.Contrato = Contrato;
            this.Mensagem = Mensagem;
            this.Comprovante = Comprovante;
        }
        
        /// <summary>
        /// Código do contrato.
        /// </summary>
        /// <value>Código do contrato.</value>
        [DataMember(Name="contrato", EmitDefaultValue=false)]
        public string Contrato { get; set; }

        /// <summary>
        /// Mensagem do retorno do cancelamento.
        /// </summary>
        /// <value>Mensagem do retorno do cancelamento.</value>
        [DataMember(Name="mensagem", EmitDefaultValue=false)]
        public string Mensagem { get; set; }

        /// <summary>
        /// Comprovante de Cancelamento no seguinte formato.
        /// </summary>
        /// <value>Comprovante de Cancelamento no seguinte formato.</value>
        [DataMember(Name="comprovante", EmitDefaultValue=false)]
        public string Comprovante { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CancelamentoContratoResponse {\n");
            sb.Append("  Contrato: ").Append(Contrato).Append("\n");
            sb.Append("  Mensagem: ").Append(Mensagem).Append("\n");
            sb.Append("  Comprovante: ").Append(Comprovante).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CancelamentoContratoResponse);
        }

        /// <summary>
        /// Returns true if CancelamentoContratoResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CancelamentoContratoResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CancelamentoContratoResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Contrato == input.Contrato ||
                    (this.Contrato != null &&
                    this.Contrato.Equals(input.Contrato))
                ) && 
                (
                    this.Mensagem == input.Mensagem ||
                    (this.Mensagem != null &&
                    this.Mensagem.Equals(input.Mensagem))
                ) && 
                (
                    this.Comprovante == input.Comprovante ||
                    (this.Comprovante != null &&
                    this.Comprovante.Equals(input.Comprovante))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Contrato != null)
                    hashCode = hashCode * 59 + this.Contrato.GetHashCode();
                if (this.Mensagem != null)
                    hashCode = hashCode * 59 + this.Mensagem.GetHashCode();
                if (this.Comprovante != null)
                    hashCode = hashCode * 59 + this.Comprovante.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
