/* 
 * Gestão de Contratos
 *
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Enumeration das situações de uma parcela.
    /// </summary>
    /// <value>Enumeration das situações de uma parcela.</value>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum SituacaoParcela
    {

        /// <summary>
        /// Enum ABERTA for value: ABERTA
        /// </summary>
        [EnumMember(Value = "ABERTA")]
        ABERTA = 1,

        /// <summary>
        /// Enum LIQUIDADA for value: LIQUIDADA
        /// </summary>        
        [EnumMember(Value = "LIQUIDADA")]
        LIQUIDADA = 2,

        /// <summary>
        /// Enum CANCELADA for value: CANCELADA
        /// </summary>

        [EnumMember(Value = "CANCELADA")]
        CANCELADA = 3
    }

}
