/* 
 * Gestão de Contratos
 *
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Enumeration dos status de um contrato.
    /// </summary>
    /// <value>Enumeration dos status de um contrato.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum StatusContrato
    {
        
        /// <summary>
        /// Enum ATRASADO for value: ATRASADO
        /// </summary>
        [EnumMember(Value = "ATRASADO")]
        ATRASADO = 1,
        
        /// <summary>
        /// Enum EMDIA for value: EM_DIA
        /// </summary>
        [EnumMember(Value = "EM_DIA")]
        EMDIA = 2
    }

}
