/* 
 * Gestão de Contratos
 *
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CancelamentoContratoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CancelamentoContratoResponseTests
    {
        // TODO uncomment below to declare an instance variable for CancelamentoContratoResponse
        //private CancelamentoContratoResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CancelamentoContratoResponse
            //instance = new CancelamentoContratoResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CancelamentoContratoResponse
        /// </summary>
        [Test]
        public void CancelamentoContratoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CancelamentoContratoResponse
            //Assert.IsInstanceOfType<CancelamentoContratoResponse> (instance, "variable 'instance' is a CancelamentoContratoResponse");
        }


        /// <summary>
        /// Test the property 'Contrato'
        /// </summary>
        [Test]
        public void ContratoTest()
        {
            // TODO unit test for the property 'Contrato'
        }
        /// <summary>
        /// Test the property 'Mensagem'
        /// </summary>
        [Test]
        public void MensagemTest()
        {
            // TODO unit test for the property 'Mensagem'
        }
        /// <summary>
        /// Test the property 'Comprovante'
        /// </summary>
        [Test]
        public void ComprovanteTest()
        {
            // TODO unit test for the property 'Comprovante'
        }

    }

}
