/* 
 * Gestão de Contratos
 *
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ErroResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ErroResponseTests
    {
        // TODO uncomment below to declare an instance variable for ErroResponse
        //private ErroResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ErroResponse
            //instance = new ErroResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ErroResponse
        /// </summary>
        [Test]
        public void ErroResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ErroResponse
            //Assert.IsInstanceOfType<ErroResponse> (instance, "variable 'instance' is a ErroResponse");
        }


        /// <summary>
        /// Test the property 'Mensagem'
        /// </summary>
        [Test]
        public void MensagemTest()
        {
            // TODO unit test for the property 'Mensagem'
        }
        /// <summary>
        /// Test the property 'Complemento'
        /// </summary>
        [Test]
        public void ComplementoTest()
        {
            // TODO unit test for the property 'Complemento'
        }

    }

}
