/* 
 * Gestão de Contratos
 *
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetContratosResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetContratosResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetContratosResponse
        //private GetContratosResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetContratosResponse
            //instance = new GetContratosResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetContratosResponse
        /// </summary>
        [Test]
        public void GetContratosResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetContratosResponse
            //Assert.IsInstanceOfType<GetContratosResponse> (instance, "variable 'instance' is a GetContratosResponse");
        }


        /// <summary>
        /// Test the property 'CpfCliente'
        /// </summary>
        [Test]
        public void CpfClienteTest()
        {
            // TODO unit test for the property 'CpfCliente'
        }
        /// <summary>
        /// Test the property 'NomeCliente'
        /// </summary>
        [Test]
        public void NomeClienteTest()
        {
            // TODO unit test for the property 'NomeCliente'
        }
        /// <summary>
        /// Test the property 'Contratos'
        /// </summary>
        [Test]
        public void ContratosTest()
        {
            // TODO unit test for the property 'Contratos'
        }

    }

}
