/* 
 * Gestão de Contratos
 *
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetContratosParcelaResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetContratosParcelaResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetContratosParcelaResponse
        //private GetContratosParcelaResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetContratosParcelaResponse
            //instance = new GetContratosParcelaResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetContratosParcelaResponse
        /// </summary>
        [Test]
        public void GetContratosParcelaResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetContratosParcelaResponse
            //Assert.IsInstanceOfType<GetContratosParcelaResponse> (instance, "variable 'instance' is a GetContratosParcelaResponse");
        }


        /// <summary>
        /// Test the property 'NumeroParcela'
        /// </summary>
        [Test]
        public void NumeroParcelaTest()
        {
            // TODO unit test for the property 'NumeroParcela'
        }
        /// <summary>
        /// Test the property 'DataVencimento'
        /// </summary>
        [Test]
        public void DataVencimentoTest()
        {
            // TODO unit test for the property 'DataVencimento'
        }
        /// <summary>
        /// Test the property 'PMT'
        /// </summary>
        [Test]
        public void PMTTest()
        {
            // TODO unit test for the property 'PMT'
        }
        /// <summary>
        /// Test the property 'NumeroDiasAtraso'
        /// </summary>
        [Test]
        public void NumeroDiasAtrasoTest()
        {
            // TODO unit test for the property 'NumeroDiasAtraso'
        }
        /// <summary>
        /// Test the property 'PercentualMulta'
        /// </summary>
        [Test]
        public void PercentualMultaTest()
        {
            // TODO unit test for the property 'PercentualMulta'
        }
        /// <summary>
        /// Test the property 'ValorMulta'
        /// </summary>
        [Test]
        public void ValorMultaTest()
        {
            // TODO unit test for the property 'ValorMulta'
        }
        /// <summary>
        /// Test the property 'PercentualJurosAtraso'
        /// </summary>
        [Test]
        public void PercentualJurosAtrasoTest()
        {
            // TODO unit test for the property 'PercentualJurosAtraso'
        }
        /// <summary>
        /// Test the property 'ValorJurosAtraso'
        /// </summary>
        [Test]
        public void ValorJurosAtrasoTest()
        {
            // TODO unit test for the property 'ValorJurosAtraso'
        }
        /// <summary>
        /// Test the property 'ValorIOFAtraso'
        /// </summary>
        [Test]
        public void ValorIOFAtrasoTest()
        {
            // TODO unit test for the property 'ValorIOFAtraso'
        }
        /// <summary>
        /// Test the property 'ValorDescontos'
        /// </summary>
        [Test]
        public void ValorDescontosTest()
        {
            // TODO unit test for the property 'ValorDescontos'
        }
        /// <summary>
        /// Test the property 'Despesas'
        /// </summary>
        [Test]
        public void DespesasTest()
        {
            // TODO unit test for the property 'Despesas'
        }
        /// <summary>
        /// Test the property 'ValorSaldoParcela'
        /// </summary>
        [Test]
        public void ValorSaldoParcelaTest()
        {
            // TODO unit test for the property 'ValorSaldoParcela'
        }

    }

}
