/* 
 * Gestão de Contratos
 *
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetParcelasResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetParcelasResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetParcelasResponse
        //private GetParcelasResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetParcelasResponse
            //instance = new GetParcelasResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetParcelasResponse
        /// </summary>
        [Test]
        public void GetParcelasResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetParcelasResponse
            //Assert.IsInstanceOfType<GetParcelasResponse> (instance, "variable 'instance' is a GetParcelasResponse");
        }


        /// <summary>
        /// Test the property 'Parcelas'
        /// </summary>
        [Test]
        public void ParcelasTest()
        {
            // TODO unit test for the property 'Parcelas'
        }

    }

}
