/* 
 * Gestão de Contratos
 *
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetParcelasParcelaResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetParcelasParcelaResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetParcelasParcelaResponse
        //private GetParcelasParcelaResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetParcelasParcelaResponse
            //instance = new GetParcelasParcelaResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetParcelasParcelaResponse
        /// </summary>
        [Test]
        public void GetParcelasParcelaResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetParcelasParcelaResponse
            //Assert.IsInstanceOfType<GetParcelasParcelaResponse> (instance, "variable 'instance' is a GetParcelasParcelaResponse");
        }


        /// <summary>
        /// Test the property 'CodigoContrato'
        /// </summary>
        [Test]
        public void CodigoContratoTest()
        {
            // TODO unit test for the property 'CodigoContrato'
        }
        /// <summary>
        /// Test the property 'ValorPago'
        /// </summary>
        [Test]
        public void ValorPagoTest()
        {
            // TODO unit test for the property 'ValorPago'
        }
        /// <summary>
        /// Test the property 'NumeroParcela'
        /// </summary>
        [Test]
        public void NumeroParcelaTest()
        {
            // TODO unit test for the property 'NumeroParcela'
        }
        /// <summary>
        /// Test the property 'DataPagamento'
        /// </summary>
        [Test]
        public void DataPagamentoTest()
        {
            // TODO unit test for the property 'DataPagamento'
        }
        /// <summary>
        /// Test the property 'Operador'
        /// </summary>
        [Test]
        public void OperadorTest()
        {
            // TODO unit test for the property 'Operador'
        }
        /// <summary>
        /// Test the property 'NSU'
        /// </summary>
        [Test]
        public void NSUTest()
        {
            // TODO unit test for the property 'NSU'
        }
        /// <summary>
        /// Test the property 'DataVencimento'
        /// </summary>
        [Test]
        public void DataVencimentoTest()
        {
            // TODO unit test for the property 'DataVencimento'
        }
        /// <summary>
        /// Test the property 'PMT'
        /// </summary>
        [Test]
        public void PMTTest()
        {
            // TODO unit test for the property 'PMT'
        }
        /// <summary>
        /// Test the property 'ValorSaldoParcela'
        /// </summary>
        [Test]
        public void ValorSaldoParcelaTest()
        {
            // TODO unit test for the property 'ValorSaldoParcela'
        }
        /// <summary>
        /// Test the property 'Situacao'
        /// </summary>
        [Test]
        public void SituacaoTest()
        {
            // TODO unit test for the property 'Situacao'
        }

    }

}
