/* 
 * Gestão de Contratos
 *
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SituacaoParcela
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SituacaoParcelaTests
    {
        // TODO uncomment below to declare an instance variable for SituacaoParcela
        //private SituacaoParcela instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SituacaoParcela
            //instance = new SituacaoParcela();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SituacaoParcela
        /// </summary>
        [Test]
        public void SituacaoParcelaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SituacaoParcela
            //Assert.IsInstanceOfType<SituacaoParcela> (instance, "variable 'instance' is a SituacaoParcela");
        }



    }

}
