/* 
 * Gestão de Contratos
 *
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SolicitacaoPagamentoRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SolicitacaoPagamentoRequestTests
    {
        // TODO uncomment below to declare an instance variable for SolicitacaoPagamentoRequest
        //private SolicitacaoPagamentoRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SolicitacaoPagamentoRequest
            //instance = new SolicitacaoPagamentoRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SolicitacaoPagamentoRequest
        /// </summary>
        [Test]
        public void SolicitacaoPagamentoRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SolicitacaoPagamentoRequest
            //Assert.IsInstanceOfType<SolicitacaoPagamentoRequest> (instance, "variable 'instance' is a SolicitacaoPagamentoRequest");
        }


        /// <summary>
        /// Test the property 'QuantidadeParcelas'
        /// </summary>
        [Test]
        public void QuantidadeParcelasTest()
        {
            // TODO unit test for the property 'QuantidadeParcelas'
        }
        /// <summary>
        /// Test the property 'ValorPagamento'
        /// </summary>
        [Test]
        public void ValorPagamentoTest()
        {
            // TODO unit test for the property 'ValorPagamento'
        }
        /// <summary>
        /// Test the property 'Operador'
        /// </summary>
        [Test]
        public void OperadorTest()
        {
            // TODO unit test for the property 'Operador'
        }

    }

}
