/* 
 * Gestão de Contratos
 *
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SolicitacaoPagamentoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SolicitacaoPagamentoResponseTests
    {
        // TODO uncomment below to declare an instance variable for SolicitacaoPagamentoResponse
        //private SolicitacaoPagamentoResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SolicitacaoPagamentoResponse
            //instance = new SolicitacaoPagamentoResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SolicitacaoPagamentoResponse
        /// </summary>
        [Test]
        public void SolicitacaoPagamentoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SolicitacaoPagamentoResponse
            //Assert.IsInstanceOfType<SolicitacaoPagamentoResponse> (instance, "variable 'instance' is a SolicitacaoPagamentoResponse");
        }


        /// <summary>
        /// Test the property 'NSU'
        /// </summary>
        [Test]
        public void NSUTest()
        {
            // TODO unit test for the property 'NSU'
        }
        /// <summary>
        /// Test the property 'DataPagamento'
        /// </summary>
        [Test]
        public void DataPagamentoTest()
        {
            // TODO unit test for the property 'DataPagamento'
        }
        /// <summary>
        /// Test the property 'ComprovantePagamento'
        /// </summary>
        [Test]
        public void ComprovantePagamentoTest()
        {
            // TODO unit test for the property 'ComprovantePagamento'
        }
        /// <summary>
        /// Test the property 'NomeCliente'
        /// </summary>
        [Test]
        public void NomeClienteTest()
        {
            // TODO unit test for the property 'NomeCliente'
        }
        /// <summary>
        /// Test the property 'CpfCliente'
        /// </summary>
        [Test]
        public void CpfClienteTest()
        {
            // TODO unit test for the property 'CpfCliente'
        }
        /// <summary>
        /// Test the property 'Parcelas'
        /// </summary>
        [Test]
        public void ParcelasTest()
        {
            // TODO unit test for the property 'Parcelas'
        }

    }

}
