/* 
 * Gestão de Contratos
 *
 * API de Gestão de Contratos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SolicitacaoPagamentoParcelaResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SolicitacaoPagamentoParcelaResponseTests
    {
        // TODO uncomment below to declare an instance variable for SolicitacaoPagamentoParcelaResponse
        //private SolicitacaoPagamentoParcelaResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SolicitacaoPagamentoParcelaResponse
            //instance = new SolicitacaoPagamentoParcelaResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SolicitacaoPagamentoParcelaResponse
        /// </summary>
        [Test]
        public void SolicitacaoPagamentoParcelaResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SolicitacaoPagamentoParcelaResponse
            //Assert.IsInstanceOfType<SolicitacaoPagamentoParcelaResponse> (instance, "variable 'instance' is a SolicitacaoPagamentoParcelaResponse");
        }


        /// <summary>
        /// Test the property 'CodigoContrato'
        /// </summary>
        [Test]
        public void CodigoContratoTest()
        {
            // TODO unit test for the property 'CodigoContrato'
        }
        /// <summary>
        /// Test the property 'NumeroParcela'
        /// </summary>
        [Test]
        public void NumeroParcelaTest()
        {
            // TODO unit test for the property 'NumeroParcela'
        }
        /// <summary>
        /// Test the property 'PMT'
        /// </summary>
        [Test]
        public void PMTTest()
        {
            // TODO unit test for the property 'PMT'
        }
        /// <summary>
        /// Test the property 'ValorPago'
        /// </summary>
        [Test]
        public void ValorPagoTest()
        {
            // TODO unit test for the property 'ValorPago'
        }
        /// <summary>
        /// Test the property 'DataVencimento'
        /// </summary>
        [Test]
        public void DataVencimentoTest()
        {
            // TODO unit test for the property 'DataVencimento'
        }
        /// <summary>
        /// Test the property 'Situacao'
        /// </summary>
        [Test]
        public void SituacaoTest()
        {
            // TODO unit test for the property 'Situacao'
        }

    }

}
